mejor_caso: ordenacion.cpp
	g++ -Wall ordenacion.cpp -o ordenacion && ./ejecuciones.sh 1

peor_caso: ordenacion.cpp
	g++ -Wall ordenacion.cpp -o ordenacion && ./ejecuciones.sh 0

clean:
	rm ordenacion *.dat