ordenacion_optimizada: ordenacion.cpp
	g++ -Wall -O3 ordenacion.cpp -o ordenacion_optimizada

ordenacion: ordenacion.cpp
	g++ -Wall ordenacion.cpp -o ordenacion

clean:
	rm ordenacion_optimizado ordenacion tiempos_optimizados.dat